### ISSUE TITLE
Backup & Upgrade Ko on bookworm

### ISSUE THREAD

**Issue by nathanael-h** [YunoHost-Apps/monitorix_ynh#66]
Hello, 
I upgraded to Bookworm and face an issue when trying to upgrade Monitorix: the safety backup is KO, thus the upgrade cannot be done. 

Here are the logs https://paste.yunohost.org/raw/izotixoban

Relevant parts are 
```
1017 DEBUG   Executing command '['sh', '-c', '/bin/bash -x "/var/cache/yunohost/app_tmp_work_dirs/app_a_yflttz/scripts/backup"  7>&1']'
1018 DEBUG   illegal environment variable name
```

```
yunohost tools versions 

yunohost: 
  repo: testing
  version: 12.0.2
yunohost-admin: 
  repo: testing
  version: 12.0.1
moulinette: 
  repo: testing
  version: 12.0.1
ssowat: 
  repo: testing
  version: 12.0.1

```
